export const torneoSchema = {
	type: "object",
	properties: {
		id: { type: "integer" },
		nombre: { type: ["string", "null"] },
		fecha_desde: { type: ["string", "null"] },
		fecha_hasta: { type: ["string", "null"] },
		entidad_desc: { type: ["string", "null"] },
		division_desc: { type: ["string", "null"] },
		categoria_desc: { type: ["string", "null"] },
		modalidad_desc: { type: ["string", "null"] },
		genero_desc: { type: ["string", "null"] },
		tipo_equipo_desc: { type: ["string", "null"] },
		ciudad: { type: ["string", "null"] },
		mostrar_web: { type: "boolean" },
		periodo: { type: "integer" },
	},
} as const;

export const partidoSchema = {
	type: "object",
	properties: {
		id: { type: "integer" },
		local_id: { type: "integer" },
		local: { type: ["string", "null"] },
		goles_local: { type: ["integer", "null"] },
		visitante_id: { type: "integer" },
		visitante: { type: ["string", "null"] },
		goles_visitante: { type: ["integer", "null"] },
		fecha: { type: "string" },
		nro_fecha: { type: "integer" },
		nro_partido: { type: "integer" },
		club_local_id: { type: "integer" },
		pais_local_id: { type: "integer" },
		club_visitante_id: { type: "integer" },
		pais_visitante_id: { type: "integer" },
		imagen_local: { type: "string" },
		imagen_visitante: { type: "string" },
		instancia: { type: ["string", "null"] },
		torneo: { type: ["string", "null"] },
		torneo_id: { type: "integer" },
		cantidad_rondas: { type: "integer" },
		estado: { type: "integer" },
		desc_estado: { type: ["string", "null"] },
		periodo: { type: ["string", "null"] },
	},
} as const;
